In [138]:
import numpy as np
with open("Sistemas de prueba\IEEE34.atp", "r+") as f:
    lines = f.readlines()
lines_copy = lines.copy()

# Extraer Lineas de las cargas en archivo
three_phase_loads = []
single_phase_loads = []
for idx, line in enumerate(lines_copy):
    if "C Load" in line:
        if "3f" in line:
            three_phase_loads.append(lines_copy[idx:idx+4])
            
        else:
            single_phase_loads.append(lines_copy[idx:idx+2])
ti = 0.01
tf = 0.06
# ti_vect = 

In [139]:
three_phase_ti = np.random.uniform(ti, tf, (len(three_phase_loads),3))
three_phase_ti = np.around(three_phase_ti, 5)
single_phase_ti = np.random.uniform(ti, tf, len(single_phase_loads))
print(three_phase_ti)

[[0.05600464 0.0593176  0.0535043 ]
 [0.0322704  0.03553383 0.02744613]
 [0.01291107 0.03553389 0.03620814]
 [0.01915537 0.0126186  0.04762969]
 [0.01499824 0.0430637  0.03826798]
 [0.04456621 0.01306655 0.02996988]
 [0.01810649 0.02636462 0.0151775 ]
 [0.03337772 0.05983321 0.02871451]
 [0.02949898 0.01335781 0.04230957]
 [0.05155417 0.02283821 0.02473465]
 [0.04106016 0.01351739 0.01752518]
 [0.01859902 0.02336892 0.04587171]
 [0.05351435 0.04071112 0.02766848]
 [0.05497748 0.04015317 0.04300595]
 [0.03514763 0.05175714 0.04310638]
 [0.02854073 0.04467134 0.03541988]
 [0.01652087 0.03694826 0.05150025]
 [0.02703684 0.02755259 0.05759499]
 [0.03248903 0.02524364 0.0543083 ]
 [0.01216996 0.05670682 0.01765906]
 [0.03596755 0.04928769 0.05888356]
 [0.03946205 0.01688623 0.05959559]]


In [142]:
# Iterar por cada Carga
from utils.components import single_phase_switch, three_phase_switch
for load_idx, loads in enumerate(three_phase_loads):
    print("\n")
    switch = three_phase_switch.copy()
    for idx, load in enumerate(loads):
        print(load, end='')
        
        if idx == 0:
            load_node = f"L{load_idx}"
            continue

        node_1 = load[2:8]
        phase_1 = node_1.strip()[-1]
        phase_2 = ''
        node_2 = load[8:14].strip()
        R = load[30:42]
        X = load[46:58]
        load_node_phase = f"{load_node}{phase_1}".center(6)
        load_node_phase_2 = ''.center(6)
        if node_2:
            phase_2 = node_2[-1]
            load_node_phase_2 = f"{load_node}{phase_2}".center(6)
        node_2 = node_2.center(6)
        switch_ln = switch[idx]
        ti = str(three_phase_ti[load_idx, idx-1]).center(10)
        tff = str(tf).center(10)
        
        
        # Create new Lines
        switch[idx] = f"{switch_ln[:2]}{node_1}{load_node_phase}{ti}{tff}{switch_ln[34:]}"
        loads[idx] = f"{load[:2]}{load_node_phase}{load_node_phase_2}{load[14:]}"
        print(loads[idx])
        print(switch[idx])
        

        





C Load 860 3fy
   L0A                        6300.9146341    5040.7317073                     0
   L0A                        6300.9146341    5040.7317073                     0

   L0A   L0A  0.05600464182370597   0.06                                                0

   L0B                        6300.9146341    5040.7317073                     0
   L0B                        6300.9146341    5040.7317073                     0

   L0B   L0B  0.05931760406021565   0.06                                                0

   L0C                        6300.9146341    5040.7317073                     0
   L0C                        6300.9146341    5040.7317073                     0

   L0C   L0C  0.0535043019683148   0.06                                                0



C Load 840 3fy
   L1A                        14307.923077    11128.384615                     0
   L1A                        14307.923077    11128.384615                     0

   L1A   L1A  0.03227039816816036   0.06  

In [105]:
for loads in three_phase_loads:
    print('\n')
    for load in loads:
        print(load, end='')



C Load 860 3fy
   L0A                        6300.9146341    5040.7317073                     0
   L0B                        6300.9146341    5040.7317073                     0
   L0C                        6300.9146341    5040.7317073                     0


C Load 840 3fy
   L1A                        14307.923077    11128.384615                     0
   L1B                        14307.923077    11128.384615                     0
   L1C                        14307.923077    11128.384615                     0


C Load 844 3f
   L2A                        953.86153846    741.89230769                     0
   L2B                        953.86153846    741.89230769                     0
   L2C                        953.86153846    741.89230769                     0


C Load 830 3f
   L3A   L3B                       49600.8         24800.4                     0
   L3B   L3C                       49600.8         24800.4                     0
   L3C   L3A                  21379.655172 

In [132]:
a = "  R1A   N100A        -1.      1.E3                                             0"
print(a[21:25])

-1. 
